#!/usr/bin/env bats

# test_report_real_media.bats - Tests using real media files with metadata
# Tests: Real metadata extraction, device detection, GPS analysis, etc.

setup() {
    export TEST_DIR="$(mktemp -d)"
    export SCRIPT_DIR="$(cd "$(dirname "$BATS_TEST_FILENAME")/.." && pwd)"
    export REPORT_SCRIPT="$SCRIPT_DIR/generate_media_report.sh"
    export FIXTURES_DIR="$SCRIPT_DIR/tests/fixtures"
    
    # Create test directory structure
    mkdir -p "$TEST_DIR/photos"
    mkdir -p "$TEST_DIR/videos"
    
    # Copy real media files with metadata
    cp "$FIXTURES_DIR/test_canon.jpg" "$TEST_DIR/photos/canon_eos.jpg"
    cp "$FIXTURES_DIR/test_nikon.jpg" "$TEST_DIR/photos/nikon_d850.jpg"
    cp "$FIXTURES_DIR/test_iphone.mov" "$TEST_DIR/videos/iphone_video.mov"
    cp "$FIXTURES_DIR/test_android.mp4" "$TEST_DIR/videos/android_video.mp4"
    
    chmod +x "$REPORT_SCRIPT"
}

teardown() {
    rm -rf "$TEST_DIR"
}

@test "basic report with real media" {
    run "$REPORT_SCRIPT" "$TEST_DIR" -r
    [ "$status" -eq 0 ]
    [[ "$output" =~ "MEDIA REPORT" ]]
    [[ "$output" =~ "Total files" ]]
}

@test "detailed report with real media" {
    run "$REPORT_SCRIPT" "$TEST_DIR" -r -d
    [ "$status" -eq 0 ]
    [[ "$output" =~ "MEDIA REPORT" ]]
    [[ "$output" =~ "KEYWORD CLUSTERS" ]]
}

@test "JSON export with real media" {
    run "$REPORT_SCRIPT" "$TEST_DIR" -r --json
    [ "$status" -eq 0 ]
    [[ "$output" =~ "directory" ]]
}

@test "CSV export with real media" {
    run "$REPORT_SCRIPT" "$TEST_DIR" -r --csv
    [ "$status" -eq 0 ]
    [[ "$output" =~ "file,type,format" ]]
}

@test "HTML export with real media" {
    run "$REPORT_SCRIPT" "$TEST_DIR" -r --html
    [ "$status" -eq 0 ]
    [[ "$output" =~ "</html>" ]]
}

@test "Markdown export with real media" {
    run "$REPORT_SCRIPT" "$TEST_DIR" -r --markdown
    [ "$status" -eq 0 ]
    [[ "$output" =~ "Report generated by" ]]
}

@test "XML export with real media" {
    run "$REPORT_SCRIPT" "$TEST_DIR" -r --xml
    [ "$status" -eq 0 ]
    [[ "$output" =~ "<?xml" ]]
}

@test "images only filter with real media" {
    run "$REPORT_SCRIPT" "$TEST_DIR" --images-only -r
    [ "$status" -eq 0 ]
    [[ "$output" =~ "MEDIA REPORT" ]]
}

@test "videos only filter with real media" {
    run "$REPORT_SCRIPT" "$TEST_DIR" --videos-only -r
    [ "$status" -eq 0 ]
    [[ "$output" =~ "MEDIA REPORT" ]]
}

@test "size filtering with real media" {
    run "$REPORT_SCRIPT" "$TEST_DIR" --min-size "1MB" -r
    [ "$status" -eq 0 ]
    [[ "$output" =~ "MEDIA REPORT" ]]
}

@test "date filtering with real media" {
    run "$REPORT_SCRIPT" "$TEST_DIR" --date-from "2020-01-01" -r
    [ "$status" -eq 0 ]
    [[ "$output" =~ "MEDIA REPORT" ]]
}

@test "complex filtering with real media" {
    run "$REPORT_SCRIPT" "$TEST_DIR" --images-only --min-size "1MB" -r
    [ "$status" -eq 0 ]
    [[ "$output" =~ "MEDIA REPORT" ]]
}

@test "save report to file with real media" {
    local report_file="$TEST_DIR/report.txt"
    run "$REPORT_SCRIPT" "$TEST_DIR" -r --save-report "$report_file"
    [ "$status" -eq 0 ]
    [ -f "$report_file" ]
    [[ "$(cat "$report_file")" =~ "MEDIA REPORT" ]]
}

@test "verbose output with real media" {
    run "$REPORT_SCRIPT" "$TEST_DIR" -r -v
    [ "$status" -eq 0 ]
    [[ "$output" =~ "MEDIA REPORT" ]]
    [[ "$output" =~ "PROCESSING FILES" ]]
} 